# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC -Dfile.encoding=UTF-8

# Parallel building aur caching performance boost ke liye
org.gradle.parallel=true
org.gradle.caching=true

# Configuration cache
org.gradle.configuration-cache=true

# Kotlin code style
kotlin.code.style=official

# --- R8 / AGP 8+ COMPATIBLE SETTINGS ---
android.enableR8.fullMode=true